### ISSUE TITLE
Download link is wrong and conflicts with old "imagemap" plugin

### ISSUE THREAD

**Issue by fthommen** [i-net-software/dokuwiki-plugin-imagemap#9]
Hi,

the imagemap2 plugin (https://www.dokuwiki.org/plugin:imagemap2) cannot be installed by the DW Extension Manager as it seems to have the download URL of the older "imagemap" plugin (https://www.dokuwiki.org/plugin:imagemap) configured. When installing manually via URL (https://github.com/i-net-software/dokuwiki-plugin-imagemap/archive/master.zip) an URL warning is displayed:

> URL changed: Download URL has changed since last download. Check
> if the new URL is valid before updating the extension.
> New: http://www.whoopdedo.org/doku-plugins/imagemap.zip
> Old: https://github.com/i-net-software/dokuwiki-plugin-imagemap
> /archive/master.zip

A Re-Installation leads to the installation of the older "imagemap" plugin.

Please fix the plugin so that it can ba managed through the Extension Manager.

Thx
Frank

**Comment by Bwansen** [comment]
I tried installing it via Extension Manager too, received an error message, but checking the installed extensions, it seems the correct version was installed. Other than that, Extension Manager shows the same behavior as described above ("URL has changed" message, re-install gives me the other imagemap plugin).

**Comment by gamma** [comment]
I'll have a look.

**Comment by PPPCR** [comment]
Same problem for me on a clean dokuwiki installation 2016-06-26a "Elenor of Tsort"

**Comment by PPPCR** [comment]
I'm not an expert at dokuwiki and it's plugins, but maybe the problem is in plugin.info.txt the value of "base" is defined to "imagemap", which is the name of the old version on https://www.dokuwiki.org/plugin:imagemap. Changing it to "imagemap**2**" seems to solve the wrong URL.
However, forcing DokuWiki to reinstall the plugin results in errors. Of course, some more renaming to make this version independent of the previous one, or completely replacing the old version is required. But as mentioned before, I'm not an expert in this.
